-- RecallNext schema contract for Exasol Personal.
-- This script is intentionally non-destructive and can be run repeatedly.

CREATE SCHEMA IF NOT EXISTS RECALLNEXT;
OPEN SCHEMA RECALLNEXT;

CREATE TABLE IF NOT EXISTS INCIDENT (
    INCIDENT_ID VARCHAR(64) NOT NULL,
    INCIDENT_VERSION DECIMAL(18, 0) NOT NULL,
    SNAPSHOT_VERSION DECIMAL(18, 0) NOT NULL,
    PRODUCT_ID VARCHAR(64) NOT NULL,
    WINDOW_START TIMESTAMP,
    WINDOW_END TIMESTAMP,
    STATUS VARCHAR(32) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_INCIDENT PRIMARY KEY (INCIDENT_ID, INCIDENT_VERSION)
);

CREATE TABLE IF NOT EXISTS LOT (
    LOT_ID VARCHAR(257) NOT NULL,
    LOT_CODE VARCHAR(128) NOT NULL,
    LOT_SOURCE_ID VARCHAR(128) NOT NULL,
    PRODUCT_ID VARCHAR(64) NOT NULL,
    QUANTITY_CASES DECIMAL(18, 0) NOT NULL,
    RECALLED BOOLEAN NOT NULL,
    RECEIVED_AT TIMESTAMP,
    LOCATION_ID VARCHAR(64),
    SOURCE_EVENT_ID VARCHAR(64),
    CONSTRAINT PK_LOT PRIMARY KEY (LOT_ID)
);

CREATE TABLE IF NOT EXISTS INCIDENT_RECALLED_LOT (
    INCIDENT_ID VARCHAR(64) NOT NULL,
    INCIDENT_VERSION DECIMAL(18, 0) NOT NULL,
    LOT_ID VARCHAR(257) NOT NULL,
    CONSTRAINT PK_INCIDENT_RECALLED_LOT
        PRIMARY KEY (INCIDENT_ID, INCIDENT_VERSION, LOT_ID)
);

CREATE TABLE IF NOT EXISTS CONTAINER (
    CONTAINER_ID VARCHAR(64) NOT NULL,
    LOT_ID VARCHAR(257),
    PRODUCT_ID VARCHAR(64) NOT NULL,
    QUANTITY_CASES DECIMAL(18, 0) NOT NULL,
    HOMOGENEITY_VERIFIED BOOLEAN NOT NULL,
    LOCATION_ID VARCHAR(64),
    SOURCE_EVENT_ID VARCHAR(64),
    CONSTRAINT PK_CONTAINER PRIMARY KEY (CONTAINER_ID)
);

CREATE TABLE IF NOT EXISTS SHIPMENT (
    SHIPMENT_ID VARCHAR(64) NOT NULL,
    PRODUCT_ID VARCHAR(64) NOT NULL,
    ORIGIN_LOCATION_ID VARCHAR(64),
    DESTINATION_ID VARCHAR(64) NOT NULL,
    SHIP_TIME TIMESTAMP,
    QUANTITY_CASES DECIMAL(18, 0) NOT NULL,
    CONSTRAINT PK_SHIPMENT PRIMARY KEY (SHIPMENT_ID)
);

CREATE TABLE IF NOT EXISTS SHIPMENT_CONTAINER (
    SHIPMENT_ID VARCHAR(64) NOT NULL,
    CONTAINER_ID VARCHAR(64) NOT NULL,
    PICK_QUANTITY_CASES DECIMAL(18, 0) NOT NULL,
    PICK_RECORD_ID VARCHAR(64),
    CONSTRAINT PK_SHIPMENT_CONTAINER PRIMARY KEY (SHIPMENT_ID, CONTAINER_ID)
);

CREATE TABLE IF NOT EXISTS EVENT (
    EVENT_ID VARCHAR(64) NOT NULL,
    EVENT_TYPE VARCHAR(64) NOT NULL,
    EVENT_TIME TIMESTAMP,
    RECORDED_AT TIMESTAMP NOT NULL,
    SOURCE_DOCUMENT_ID VARCHAR(128),
    SOURCE_SYSTEM VARCHAR(64) NOT NULL,
    SNAPSHOT_VERSION DECIMAL(18, 0) NOT NULL,
    CONSTRAINT PK_EVENT PRIMARY KEY (EVENT_ID)
);

CREATE TABLE IF NOT EXISTS SOURCE_COVERAGE (
    INCIDENT_ID VARCHAR(64) NOT NULL,
    INCIDENT_VERSION DECIMAL(18, 0) NOT NULL,
    SOURCE_SYSTEM VARCHAR(64) NOT NULL,
    EXPECTED_RECORDS DECIMAL(18, 0) NOT NULL,
    RECEIVED_RECORDS DECIMAL(18, 0) NOT NULL,
    IS_COMPLETE BOOLEAN NOT NULL,
    ISSUE_DETAIL VARCHAR(2000),
    CONSTRAINT PK_SOURCE_COVERAGE
        PRIMARY KEY (INCIDENT_ID, INCIDENT_VERSION, SOURCE_SYSTEM)
);

CREATE TABLE IF NOT EXISTS REQUIRED_SOURCE_SYSTEM (
    INCIDENT_ID VARCHAR(64) NOT NULL,
    INCIDENT_VERSION DECIMAL(18, 0) NOT NULL,
    SOURCE_SYSTEM VARCHAR(64) NOT NULL,
    CONSTRAINT PK_REQUIRED_SOURCE_SYSTEM
        PRIMARY KEY (INCIDENT_ID, INCIDENT_VERSION, SOURCE_SYSTEM)
);

CREATE TABLE IF NOT EXISTS EVIDENCE_ACTION (
    ACTION_ID VARCHAR(64) NOT NULL,
    INCIDENT_ID VARCHAR(64) NOT NULL,
    INCIDENT_VERSION DECIMAL(18, 0) NOT NULL,
    ACTION_TYPE VARCHAR(64) NOT NULL,
    TARGET_TYPE VARCHAR(32) NOT NULL,
    TARGET_ID VARCHAR(64) NOT NULL,
    QUESTION VARCHAR(2000) NOT NULL,
    ESTIMATED_MINUTES DECIMAL(18, 0) NOT NULL,
    AVAILABILITY VARCHAR(32) NOT NULL,
    CONSTRAINT PK_EVIDENCE_ACTION PRIMARY KEY (ACTION_ID)
);

CREATE TABLE IF NOT EXISTS ACTION_SHIPMENT (
    ACTION_ID VARCHAR(64) NOT NULL,
    SHIPMENT_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_ACTION_SHIPMENT PRIMARY KEY (ACTION_ID, SHIPMENT_ID)
);

CREATE TABLE IF NOT EXISTS EVIDENCE (
    EVIDENCE_ID VARCHAR(64) NOT NULL,
    ACTION_ID VARCHAR(64) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    FACT_JSON VARCHAR(20000),
    SOURCE_REFERENCE VARCHAR(2000),
    CONTENT_HASH VARCHAR(128),
    VERIFIED_BY VARCHAR(128),
    INCIDENT_VERSION DECIMAL(18, 0) NOT NULL,
    CONSTRAINT PK_EVIDENCE PRIMARY KEY (EVIDENCE_ID)
);

CREATE TABLE IF NOT EXISTS SHIPMENT_DECISION (
    INCIDENT_ID VARCHAR(64) NOT NULL,
    INCIDENT_VERSION DECIMAL(18, 0) NOT NULL,
    SHIPMENT_ID VARCHAR(64) NOT NULL,
    MIN_RECALLED_CASES DECIMAL(18, 0) NOT NULL,
    MAX_RECALLED_CASES DECIMAL(18, 0) NOT NULL,
    STATUS VARCHAR(64) NOT NULL,
    SOLVER_STATUS VARCHAR(64) NOT NULL,
    ASSUMPTIONS_JSON VARCHAR(20000) NOT NULL,
    EVIDENCE_REFERENCES_JSON VARCHAR(20000) NOT NULL,
    MODEL_VERSION VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_SHIPMENT_DECISION
        PRIMARY KEY (INCIDENT_ID, INCIDENT_VERSION, SHIPMENT_ID)
);

CREATE TABLE IF NOT EXISTS ALLOCATION_SCENARIO (
    INCIDENT_ID VARCHAR(64) NOT NULL,
    INCIDENT_VERSION DECIMAL(18, 0) NOT NULL,
    SCENARIO_ID VARCHAR(64) NOT NULL,
    CANDIDATE_UNIVERSE_COMPLETE BOOLEAN NOT NULL,
    SOLVER_STATUS VARCHAR(64) NOT NULL,
    MODEL_VERSION VARCHAR(64) NOT NULL,
    ASSUMPTIONS_JSON VARCHAR(20000) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_ALLOCATION_SCENARIO
        PRIMARY KEY (INCIDENT_ID, INCIDENT_VERSION, SCENARIO_ID)
);

CREATE TABLE IF NOT EXISTS SCENARIO_ALLOCATION (
    INCIDENT_ID VARCHAR(64) NOT NULL,
    INCIDENT_VERSION DECIMAL(18, 0) NOT NULL,
    SCENARIO_ID VARCHAR(64) NOT NULL,
    SHIPMENT_ID VARCHAR(64) NOT NULL,
    LOT_ID VARCHAR(257) NOT NULL,
    QUANTITY_CASES DECIMAL(18, 0) NOT NULL,
    CONSTRAINT PK_SCENARIO_ALLOCATION
        PRIMARY KEY (
            INCIDENT_ID,
            INCIDENT_VERSION,
            SCENARIO_ID,
            SHIPMENT_ID,
            LOT_ID
        )
);
