-- Conservative completeness and data-quality gates.
OPEN SCHEMA RECALLNEXT;

CREATE OR REPLACE VIEW V_DATA_QUALITY_ISSUE AS
SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'NO_SOURCE_COVERAGE_DECLARED' AS ISSUE_CODE,
    'INCIDENT' AS ENTITY_TYPE,
    I.INCIDENT_ID AS ENTITY_ID,
    'No source-coverage declaration exists; completeness cannot be assumed.' AS DETAIL
FROM INCIDENT I
LEFT JOIN SOURCE_COVERAGE C
  ON C.INCIDENT_ID = I.INCIDENT_ID
 AND C.INCIDENT_VERSION = I.INCIDENT_VERSION
WHERE C.INCIDENT_ID IS NULL

UNION ALL

SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'NO_REQUIRED_SOURCE_DECLARED' AS ISSUE_CODE,
    'INCIDENT' AS ENTITY_TYPE,
    I.INCIDENT_ID AS ENTITY_ID,
    'No required source-system roster exists; completeness cannot be established.' AS DETAIL
FROM INCIDENT I
LEFT JOIN REQUIRED_SOURCE_SYSTEM R
  ON R.INCIDENT_ID = I.INCIDENT_ID
 AND R.INCIDENT_VERSION = I.INCIDENT_VERSION
WHERE R.INCIDENT_ID IS NULL

UNION ALL

SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'MISSING_REQUIRED_SOURCE_COVERAGE' AS ISSUE_CODE,
    'SOURCE_SYSTEM' AS ENTITY_TYPE,
    R.SOURCE_SYSTEM AS ENTITY_ID,
    'A required source system has no coverage declaration.' AS DETAIL
FROM INCIDENT I
JOIN REQUIRED_SOURCE_SYSTEM R
  ON R.INCIDENT_ID = I.INCIDENT_ID
 AND R.INCIDENT_VERSION = I.INCIDENT_VERSION
LEFT JOIN SOURCE_COVERAGE C
  ON C.INCIDENT_ID = R.INCIDENT_ID
 AND C.INCIDENT_VERSION = R.INCIDENT_VERSION
 AND C.SOURCE_SYSTEM = R.SOURCE_SYSTEM
WHERE C.SOURCE_SYSTEM IS NULL

UNION ALL

SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'NO_RECALLED_LOT_DECLARED' AS ISSUE_CODE,
    'INCIDENT' AS ENTITY_TYPE,
    I.INCIDENT_ID AS ENTITY_ID,
    'No recalled source-qualified lot is attached to this incident version.' AS DETAIL
FROM INCIDENT I
LEFT JOIN INCIDENT_RECALLED_LOT R
  ON R.INCIDENT_ID = I.INCIDENT_ID
 AND R.INCIDENT_VERSION = I.INCIDENT_VERSION
WHERE R.INCIDENT_ID IS NULL

UNION ALL

SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'UNKNOWN_RECALLED_LOT_REFERENCE' AS ISSUE_CODE,
    'LOT' AS ENTITY_TYPE,
    R.LOT_ID AS ENTITY_ID,
    'The recalled lot reference does not exist in the accepted lot table.' AS DETAIL
FROM INCIDENT I
JOIN INCIDENT_RECALLED_LOT R
  ON R.INCIDENT_ID = I.INCIDENT_ID
 AND R.INCIDENT_VERSION = I.INCIDENT_VERSION
LEFT JOIN LOT L
  ON L.LOT_ID = R.LOT_ID
WHERE L.LOT_ID IS NULL

UNION ALL

SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'LOT_IDENTITY_MISMATCH' AS ISSUE_CODE,
    'LOT' AS ENTITY_TYPE,
    L.LOT_ID AS ENTITY_ID,
    'LOT_ID does not equal LOT_SOURCE_ID:LOT_CODE.' AS DETAIL
FROM INCIDENT I
JOIN LOT L
  ON L.PRODUCT_ID = I.PRODUCT_ID
WHERE L.LOT_ID <> L.LOT_SOURCE_ID || ':' || L.LOT_CODE

UNION ALL

SELECT DISTINCT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'DUPLICATE_LOT_SOURCE_CODE' AS ISSUE_CODE,
    'LOT' AS ENTITY_TYPE,
    D.LOT_SOURCE_ID || ':' || D.LOT_CODE AS ENTITY_ID,
    'More than one lot row has the same source-qualified lot identity.' AS DETAIL
FROM INCIDENT I
JOIN LOT L
  ON L.PRODUCT_ID = I.PRODUCT_ID
JOIN (
    SELECT LOT_SOURCE_ID, LOT_CODE
    FROM LOT
    GROUP BY LOT_SOURCE_ID, LOT_CODE
    HAVING COUNT(*) > 1
) D
  ON D.LOT_SOURCE_ID = L.LOT_SOURCE_ID
 AND D.LOT_CODE = L.LOT_CODE

UNION ALL

SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'MISSING_SOURCE_COVERAGE' AS ISSUE_CODE,
    'SOURCE_SYSTEM' AS ENTITY_TYPE,
    C.SOURCE_SYSTEM AS ENTITY_ID,
    'Expected source records are missing or coverage is unverified.' AS DETAIL
FROM INCIDENT I
JOIN SOURCE_COVERAGE C
  ON C.INCIDENT_ID = I.INCIDENT_ID
 AND C.INCIDENT_VERSION = I.INCIDENT_VERSION
WHERE C.IS_COMPLETE = FALSE
   OR C.RECEIVED_RECORDS < C.EXPECTED_RECORDS

UNION ALL

SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'SHIPMENT_QUANTITY_MISMATCH' AS ISSUE_CODE,
    'SHIPMENT' AS ENTITY_TYPE,
    S.SHIPMENT_ID AS ENTITY_ID,
    'Shipment quantity does not equal the sum of mapped pick quantities.' AS DETAIL
FROM INCIDENT I
JOIN SHIPMENT S
  ON S.PRODUCT_ID = I.PRODUCT_ID
 AND (I.WINDOW_START IS NULL OR S.SHIP_TIME IS NULL OR S.SHIP_TIME >= I.WINDOW_START)
 AND (I.WINDOW_END IS NULL OR S.SHIP_TIME IS NULL OR S.SHIP_TIME <= I.WINDOW_END)
LEFT JOIN SHIPMENT_CONTAINER SC
  ON SC.SHIPMENT_ID = S.SHIPMENT_ID
GROUP BY
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    S.SHIPMENT_ID,
    S.QUANTITY_CASES
HAVING COALESCE(SUM(SC.PICK_QUANTITY_CASES), 0) <> S.QUANTITY_CASES

UNION ALL

SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'CONTAINER_OVERALLOCATED' AS ISSUE_CODE,
    'CONTAINER' AS ENTITY_TYPE,
    C.CONTAINER_ID AS ENTITY_ID,
    'Mapped pick quantities exceed the recorded container quantity.' AS DETAIL
FROM INCIDENT I
JOIN SHIPMENT S
  ON S.PRODUCT_ID = I.PRODUCT_ID
 AND (I.WINDOW_START IS NULL OR S.SHIP_TIME IS NULL OR S.SHIP_TIME >= I.WINDOW_START)
 AND (I.WINDOW_END IS NULL OR S.SHIP_TIME IS NULL OR S.SHIP_TIME <= I.WINDOW_END)
JOIN SHIPMENT_CONTAINER SC
  ON SC.SHIPMENT_ID = S.SHIPMENT_ID
JOIN CONTAINER C
  ON C.CONTAINER_ID = SC.CONTAINER_ID
GROUP BY
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    C.CONTAINER_ID,
    C.QUANTITY_CASES
HAVING SUM(SC.PICK_QUANTITY_CASES) > C.QUANTITY_CASES

UNION ALL

SELECT DISTINCT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'PRODUCT_MISMATCH' AS ISSUE_CODE,
    'CONTAINER' AS ENTITY_TYPE,
    C.CONTAINER_ID AS ENTITY_ID,
    'Shipment and container product identifiers disagree.' AS DETAIL
FROM INCIDENT I
JOIN SHIPMENT S
  ON S.PRODUCT_ID = I.PRODUCT_ID
 AND (I.WINDOW_START IS NULL OR S.SHIP_TIME IS NULL OR S.SHIP_TIME >= I.WINDOW_START)
 AND (I.WINDOW_END IS NULL OR S.SHIP_TIME IS NULL OR S.SHIP_TIME <= I.WINDOW_END)
JOIN SHIPMENT_CONTAINER SC
  ON SC.SHIPMENT_ID = S.SHIPMENT_ID
JOIN CONTAINER C
  ON C.CONTAINER_ID = SC.CONTAINER_ID
WHERE C.PRODUCT_ID <> S.PRODUCT_ID

UNION ALL

SELECT DISTINCT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'UNKNOWN_CONTAINER_LOT_REFERENCE' AS ISSUE_CODE,
    'CONTAINER' AS ENTITY_TYPE,
    C.CONTAINER_ID AS ENTITY_ID,
    'A recorded container lot does not exist in the accepted lot table.' AS DETAIL
FROM INCIDENT I
JOIN SHIPMENT S
  ON S.PRODUCT_ID = I.PRODUCT_ID
 AND (I.WINDOW_START IS NULL OR S.SHIP_TIME IS NULL OR S.SHIP_TIME >= I.WINDOW_START)
 AND (I.WINDOW_END IS NULL OR S.SHIP_TIME IS NULL OR S.SHIP_TIME <= I.WINDOW_END)
JOIN SHIPMENT_CONTAINER SC
  ON SC.SHIPMENT_ID = S.SHIPMENT_ID
JOIN CONTAINER C
  ON C.CONTAINER_ID = SC.CONTAINER_ID
LEFT JOIN LOT L
  ON L.LOT_ID = C.LOT_ID
WHERE C.LOT_ID IS NOT NULL
  AND L.LOT_ID IS NULL

UNION ALL

SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'UNKNOWN_SHIPMENT_TIME' AS ISSUE_CODE,
    'SHIPMENT' AS ENTITY_TYPE,
    S.SHIPMENT_ID AS ENTITY_ID,
    'Shipment time is unknown, so chronology cannot narrow candidates.' AS DETAIL
FROM INCIDENT I
JOIN SHIPMENT S
  ON S.PRODUCT_ID = I.PRODUCT_ID
WHERE S.SHIP_TIME IS NULL

UNION ALL

SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    'UNKNOWN_LOT_RECEIPT_TIME' AS ISSUE_CODE,
    'LOT' AS ENTITY_TYPE,
    L.LOT_ID AS ENTITY_ID,
    'Lot receipt time is unknown, so chronology cannot narrow candidates.' AS DETAIL
FROM INCIDENT I
JOIN LOT L
  ON L.PRODUCT_ID = I.PRODUCT_ID
WHERE L.RECEIVED_AT IS NULL;

CREATE OR REPLACE VIEW V_CANDIDATE_UNIVERSE_STATUS AS
SELECT
    I.INCIDENT_ID,
    I.INCIDENT_VERSION,
    CASE WHEN COUNT(Q.ISSUE_CODE) = 0 THEN TRUE ELSE FALSE END
        AS CANDIDATE_UNIVERSE_COMPLETE,
    COUNT(Q.ISSUE_CODE) AS BLOCKING_ISSUE_COUNT
FROM INCIDENT I
LEFT JOIN V_DATA_QUALITY_ISSUE Q
  ON Q.INCIDENT_ID = I.INCIDENT_ID
 AND Q.INCIDENT_VERSION = I.INCIDENT_VERSION
GROUP BY I.INCIDENT_ID, I.INCIDENT_VERSION;

CREATE OR REPLACE VIEW V_PLANNER_SCENARIO_ALLOCATION AS
SELECT
    M.INCIDENT_ID,
    M.INCIDENT_VERSION,
    M.SCENARIO_ID,
    A.SHIPMENT_ID,
    L.LOT_SOURCE_ID,
    L.LOT_CODE,
    L.LOT_SOURCE_ID || ':' || L.LOT_CODE AS LOT_ID,
    A.QUANTITY_CASES,
    M.CANDIDATE_UNIVERSE_COMPLETE,
    M.SOLVER_STATUS,
    M.MODEL_VERSION
FROM ALLOCATION_SCENARIO M
JOIN SCENARIO_ALLOCATION A
  ON A.INCIDENT_ID = M.INCIDENT_ID
 AND A.INCIDENT_VERSION = M.INCIDENT_VERSION
 AND A.SCENARIO_ID = M.SCENARIO_ID
JOIN LOT L
  ON L.LOT_ID = A.LOT_ID;
